### ISSUE TITLE
delete messages from bots

### ISSUE THREAD

**Issue by part1cleth1ef** [napstr/Baymax#13]
I've come accross an issue where users decide to use bot commands inside the support channel which is slightly getting on my nerves, it would be conveniant if baymax was to delete bot messages after a certain timeout.

**Comment by schnapster** [comment]
Why do other bots have write access to that channel in the first place?

**Comment by part1cleth1ef** [comment]
I suppose I could just remove it, though I have a few bots which handle automod since I have tons of annoying spam of which plagues my server

**Comment by schnapster** [comment]
Understood, that sounds like a real use case I'd want to see supported 👌

**Comment by schnapster** [comment]
Feel free to give this a spin, I didn't test it 😎

**Comment by part1cleth1ef** [comment]
Thanks, I shall deploy it and test

**Comment by part1cleth1ef** [comment]
It seems to be working just fine, Thanks!
